name: identity_sender
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_bloc: ^4.0.0
  bloc: ^4.0.0
  equatable: ^1.1.1
  rxdart: ^0.23.1
  dio: ^3.0.9
  cached_network_image: ^2.1.0+1
  image_picker: ^0.6.0+9
  image: ^2.1.14
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+1
  firebase_storage: ^4.0.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true